In [3]:
import pandas as pd
import numpy as np

In [5]:
# mpg.csv dosyasını okuyun ve df değişkenine atayın.
# 1) df'in içindeki sütunların birbirleriyle olan korelasyonlarına(ilişkilerine) bakın.

df = pd.read_csv("../datas/mpg.csv")
df.select_dtypes(include="number").corr()

,mpg,cylinders,displacement,weight,acceleration,model_year,origin
mpg,1.000000,-0.775396,-0.804203,-0.831741,0.420289,0.579267,0.563450
cylinders,-0.775396,1.000000,0.950721,0.896017,-0.505419,-0.348746,-0.562543
displacement,-0.804203,0.950721,1.000000,0.932824,-0.543684,-0.370164,-0.609409
weight,-0.831741,0.896017,0.932824,1.000000,-0.417457,-0.306564,-0.581024
acceleration,0.420289,-0.505419,-0.543684,-0.417457,1.000000,0.288137,0.205873
model_year,0.579267,-0.348746,-0.370164,-0.306564,0.288137,1.000000,0.180662
origin,0.563450,-0.562543,-0.609409,-0.581024,0.205873,0.180662,1.000000

In [12]:
# 2) mpg sütunu ile diğer sütunların arasındaki korelasyonları özel olarak inceleyin.(Bunu göstermedik ama df.corr() çağırdıktan sonra aynı normal df'lerde olduğu gibi istediğiniz sütunu çağırabiliyorsunuz.)

df.corr(numeric_only=True)["mpg"]

mpg             1.000000
cylinders      -0.775396
displacement   -0.804203
weight         -0.831741
acceleration    0.420289
model_year      0.579267
origin          0.563450
Name: mpg, dtype: float64

In [13]:
# 3) cylinders sütununda hangi unique değerler olduğuna liste halinde bakın.

df["cylinders"].unique()

array([8, 4, 6, 3, 5], dtype=int64)

In [14]:
# 4) cylinders sütunundaki unique değerlerin her birinden kaçar adet olduğuna bakın.

df["cylinders"].value_counts()

cylinders
4    204
8    103
6     84
3      4
5      3
Name: count, dtype: int64

In [16]:
# 5) Arabanın modeli 75-80 yılları arasındaki arabaların hepsini getirin.(75 ve 80 dahil)

df[df["model_year"].between(75,80)]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
152,19.0,6,225.0,95,3264,16.0,75,1,plymouth valiant custom
153,18.0,6,250.0,105,3459,16.0,75,1,chevrolet nova
154,15.0,6,250.0,72,3432,21.0,75,1,mercury monarch
155,15.0,6,250.0,72,3158,19.5,75,1,ford maverick
156,16.0,8,400.0,170,4668,11.5,75,1,pontiac catalina
...,...,...,...,...,...,...,...,...,...
333,32.7,6,168.0,132,2910,11.4,80,3,datsun 280-zx
334,23.7,3,70.0,100,2420,12.5,80,3,mazda rx-7 gs
335,35.0,4,122.0,88,2500,15.1,80,2,triumph tr7 coupe
336,23.6,4,140.0,?,2905,14.3,80,1,ford mustang cobra
337,32.4,4,107.0,72,2290,17.0,80,3,honda accord

In [34]:
# 6) horsepower'ı 155-180 arasındaki arabaların hepsini getirin.(155 dahil, 180 dahil değil)(Bu sorguyu yapabilmeniz için horsepower sütununu object durumdan float duruma getirmeniz gerekiyor.)

df["horsepower"] = df["horsepower"].replace("?", np.nan)
df["horsepower"] = df["horsepower"].astype(float)
df[df["horsepower"].between(150,180, inclusive="left")]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
1,15.0,8,350.0,165.0,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,1,amc rebel sst
10,15.0,8,383.0,170.0,3563,10.0,70,1,dodge challenger se
11,14.0,8,340.0,160.0,3609,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400.0,150.0,3761,9.5,70,1,chevrolet monte carlo
38,14.0,8,350.0,165.0,4209,12.0,71,1,chevrolet impala
39,14.0,8,400.0,175.0,4464,11.5,71,1,pontiac catalina brougham
40,14.0,8,351.0,153.0,4154,13.5,71,1,ford galaxie 500
41,14.0,8,318.0,150.0,4096,13.0,71,1,plymouth fury iii
43,13.0,8,400.0,170.0,4746,12.0,71,1,ford country squire (sw)
44,13.0,8,400.0,175.0,5140,12.0,71,1,pontiac safari (sw)
62,13.0,8,350.0,165.0,4274,12.0,72,1,chevrolet impala
63,14.0,8,400.0,175.0,4385,12.0,72,1,pontiac catalina
64,15.0,8,318.0,150.0,4135,13.5,72,1,plymouth fury iii
65,14.0,8,351.0,153.0,4129,13.0,72,1,ford galaxie 500
66,17.0,8,304.0,150.0,3672,11.5,72,1,amc ambassador sst
68,13.0,8,350.0,155.0,4502,13.5,72,1,buick lesabre custom
69,12.0,8,350.0,160.0,4456,13.5,72,1,oldsmobile delta 88 royale
72,15.0,8,304.0,150.0,3892,12.5,72,1,amc matador (sw)
75,14.0,8,318.0,150.0,4077,14.0,72,1,plymouth satellite custom (sw)
85,13.0,8,350.0,175.0,4100,13.0,73,1,buick century 350
86,14.0,8,304.0,150.0,3672,11.5,73,1,amc matador
89,15.0,8,318.0,150.0,3777,12.5,73,1,dodge coronet custom
91,13.0,8,400.0,150.0,4464,12.0,73,1,chevrolet caprice classic
92,13.0,8,351.0,158.0,4363,13.0,73,1,ford ltd
93,14.0,8,318.0,150.0,4237,14.5,73,1,plymouth fury gran sedan
96,13.0,8,360.0,175.0,3821,11.0,73,1,amc ambassador brougham
103,11.0,8,400.0,150.0,4997,14.0,73,1,chevrolet impala
104,12.0,8,400.0,167.0,4906,12.5,73,1,ford country
105,13.0,8,360.0,170.0,4654,13.0,73,1,plymouth custom suburb
121,15.0,8,318.0,150.0,3399,11.0,73,1,dodge dart custom
137,13.0,8,350.0,150.0,4699,14.5,74,1,buick century luxus (sw)
138,14.0,8,318.0,150.0,4457,13.5,74,1,dodge coronet custom (sw)
140,14.0,8,304.0,150.0,4257,15.5,74,1,amc matador (sw)
156,16.0,8,400.0,170.0,4668,11.5,75,1,pontiac catalina
158,16.0,8,318.0,150.0,4498,14.5,75,1,plymouth grand fury
188,16.0,8,318.0,150.0,4190,13.0,76,1,dodge coronet brougham
190,14.5,8,351.0,152.0,4215,12.8,76,1,ford gran torino
208,13.0,8,318.0,150.0,3940,13.2,76,1,plymouth volare premier v8
215,13.0,8,318.0,150.0,3755,14.0,76,1,dodge d100
230,15.5,8,350.0,170.0,4165,11.4,77,1,chevrolet monte carlo landau
263,17.7,6,231.0,165.0,3445,13.4,78,1,buick regal sport coupe (turbo)
289,16.9,8,350.0,155.0,4360,14.9,79,1,buick estate wagon (sw)
292,18.5,8,360.0,150.0,3940,13.0,79,1,chrysler lebaron town @ country (sw)

In [46]:
# 7) Elinizdeki df'i horsepower'a göre büyükten küçüğe sıralayın ardından df'in indexlerini sıfırlayın.

df.sort_values(by="horsepower", ascending=False).reset_index(drop=True)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,16.0,8,400.0,230.0,4278,9.5,73,1,pontiac grand prix
1,12.0,8,455.0,225.0,4951,11.0,73,1,buick electra 225 custom
2,14.0,8,455.0,225.0,3086,10.0,70,1,buick estate wagon (sw)
3,14.0,8,455.0,225.0,4425,10.0,70,1,pontiac catalina
4,14.0,8,454.0,220.0,4354,9.0,70,1,chevrolet impala
...,...,...,...,...,...,...,...,...,...
393,21.0,6,200.0,NaN,2875,17.0,74,1,ford maverick
394,40.9,4,85.0,NaN,1835,17.3,80,2,renault lecar deluxe
395,23.6,4,140.0,NaN,2905,14.3,80,1,ford mustang cobra
396,34.5,4,100.0,NaN,2320,15.8,81,2,renault 18i
397,23.0,4,151.0,NaN,3035,20.5,82,1,amc concord dl

In [47]:
# 8) Elinizdeki df'den en küçük 5 acceralation'a sahip olan arabaları getirin.

df.sort_values(by="acceleration").reset_index(drop=True).head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,14.0,8,340.0,160.0,3609,8.0,70,1,plymouth 'cuda 340
1,15.0,8,390.0,190.0,3850,8.5,70,1,amc ambassador dpl
2,14.0,8,440.0,215.0,4312,8.5,70,1,plymouth fury iii
3,14.0,8,454.0,220.0,4354,9.0,70,1,chevrolet impala
4,16.0,8,400.0,230.0,4278,9.5,73,1,pontiac grand prix

In [62]:
# --- CIA_Country_Facts.csv dosyasını okuyun ve yeniden df değişkenine atayın.(Artık eski df ile işimiz kalmadığı için aynı ismi verebiliriz.)
# 9) Elimizdeki CIA'in ülkeler hakkında topladığı basit açık kaynak verileri df'inde kaç ülkenin verisi olduğunu bulun.

df = pd.read_csv("../datas/CIA_Country_Facts.csv")
df.shape[0]

227

In [63]:
# 10) Elimizdeki sütunlardan hangilerinde kaçar tane nan veri olduğunu bulun.
df.isna().sum()

Country                                0
Region                                 0
Population                             0
Area (sq. mi.)                         0
Pop. Density (per sq. mi.)             0
Coastline (coast/area ratio)           0
Net migration                          3
Infant mortality (per 1000 births)     3
GDP ($ per capita)                     1
Literacy (%)                          18
Phones (per 1000)                      4
Arable (%)                             2
Crops (%)                              2
Other (%)                              2
Climate                               22
Birthrate                              3
Deathrate                              4
Agriculture                           15
Industry                              16
Service                               15
dtype: int64

In [64]:
# 11) Elimizde tamamen nan değerlerden oluşan bir satır varsa o satırı düşürün.(Tamamen nan değerlerden oluşan bir satır olup olmadığını, herhangi bir satırın düşüp düşmediğini kontrol edin)

df.dropna(how="all")

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,48.0,0.00,23.06,163.07,700.0,36.0,3.2,12.13,0.22,87.65,1.0,46.60,20.34,0.380,0.240,0.380
1,Albania,EASTERN EUROPE,3581655,28748,124.6,1.26,-4.93,21.52,4500.0,86.5,71.2,21.09,4.42,74.49,3.0,15.11,5.22,0.232,0.188,0.579
2,Algeria,NORTHERN AFRICA,32930091,2381740,13.8,0.04,-0.39,31.00,6000.0,70.0,78.1,3.22,0.25,96.53,1.0,17.14,4.61,0.101,0.600,0.298
3,American Samoa,OCEANIA,57794,199,290.4,58.29,-20.71,9.27,8000.0,97.0,259.5,10.00,15.00,75.00,2.0,22.46,3.27,NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,152.1,0.00,6.60,4.05,19000.0,100.0,497.2,2.22,0.00,97.78,3.0,8.71,6.25,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,West Bank,NEAR EAST,2460492,5860,419.9,0.00,2.98,19.62,800.0,NaN,145.2,16.90,18.97,64.13,3.0,31.67,3.92,0.090,0.280,0.630
223,Western Sahara,NORTHERN AFRICA,273008,266000,1.0,0.42,NaN,NaN,NaN,NaN,NaN,0.02,0.00,99.98,1.0,NaN,NaN,NaN,NaN,0.400
224,Yemen,NEAR EAST,21456188,527970,40.6,0.36,0.00,61.50,800.0,50.2,37.2,2.78,0.24,96.98,1.0,42.89,8.30,0.135,0.472,0.393
225,Zambia,SUB-SAHARAN AFRICA,11502010,752614,15.3,0.00,0.00,88.29,800.0,80.6,8.2,7.08,0.03,92.90,2.0,41.00,19.93,0.220,0.290,0.489
226,Zimbabwe,SUB-SAHARAN AFRICA,12236805,390580,31.3,0.00,0.00,67.69,1900.0,90.7,26.8,8.32,0.34,91.34,2.0,28.01,21.84,0.179,0.243,0.579

In [85]:
# 12) Her Bölgedeki(Region) toplam kişi sayısına bakın.

df.groupby(by="Region")["Population"].sum()

Region
ASIA (EX. NEAR EAST)                   3687982236
BALTICS                                   7184974
C.W. OF IND. STATES                     280081548
EASTERN EUROPE                          119914717
LATIN AMER. & CARIB                     561824599
NEAR EAST                               195068377
NORTHERN AFRICA                         161407133
NORTHERN AMERICA                        331672307
OCEANIA                                  33131662
SUB-SAHARAN AFRICA                      749437000
WESTERN EUROPE                          396339998
Name: Population, dtype: int64

In [129]:
# 13) Climate değerleri nan olanlar, tüm df'in ortalama climate değeriyle doldurun.(Gerçek bir analiz yapıyor olsaydık bu çok mantıklı bir hareket olmazdı, belki her bulunduğu bölgenin ortalama climate değeriyle doldurmak daha mantıklı bir hareket olurdu. Fakat şimdilik bu kadar kasmaya gerek yok. nan değerleri tüm climate ortalamalarıyla doldursanız yeterli.)

df["Climate"] = df["Climate"].fillna(df["Climate"].mean())
df

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,48.0,0.00,23.06,163.07,700.0,36.0,3.2,12.13,0.22,87.65,1.0,46.60,20.34,0.380,0.240,0.380
1,Albania,EASTERN EUROPE,3581655,28748,124.6,1.26,-4.93,21.52,4500.0,86.5,71.2,21.09,4.42,74.49,3.0,15.11,5.22,0.232,0.188,0.579
2,Algeria,NORTHERN AFRICA,32930091,2381740,13.8,0.04,-0.39,31.00,6000.0,70.0,78.1,3.22,0.25,96.53,1.0,17.14,4.61,0.101,0.600,0.298
3,American Samoa,OCEANIA,57794,199,290.4,58.29,-20.71,9.27,8000.0,97.0,259.5,10.00,15.00,75.00,2.0,22.46,3.27,NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,152.1,0.00,6.60,4.05,19000.0,100.0,497.2,2.22,0.00,97.78,3.0,8.71,6.25,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,West Bank,NEAR EAST,2460492,5860,419.9,0.00,2.98,19.62,800.0,NaN,145.2,16.90,18.97,64.13,3.0,31.67,3.92,0.090,0.280,0.630
223,Western Sahara,NORTHERN AFRICA,273008,266000,1.0,0.42,NaN,NaN,NaN,NaN,NaN,0.02,0.00,99.98,1.0,NaN,NaN,NaN,NaN,0.400
224,Yemen,NEAR EAST,21456188,527970,40.6,0.36,0.00,61.50,800.0,50.2,37.2,2.78,0.24,96.98,1.0,42.89,8.30,0.135,0.472,0.393
225,Zambia,SUB-SAHARAN AFRICA,11502010,752614,15.3,0.00,0.00,88.29,800.0,80.6,8.2,7.08,0.03,92.90,2.0,41.00,19.93,0.220,0.290,0.489
226,Zimbabwe,SUB-SAHARAN AFRICA,12236805,390580,31.3,0.00,0.00,67.69,1900.0,90.7,26.8,8.32,0.34,91.34,2.0,28.01,21.84,0.179,0.243,0.579

In [109]:
# 14) Bölgeler ve Ülkelere göre gruplama yapın ardından Doğum miktarlarına bakın.

df.groupby(["Region", "Country"])["Birthrate"].sum().reset_index()

                                  Region         Country  Birthrate
0          ASIA (EX. NEAR EAST)              Afghanistan      46.60
1          ASIA (EX. NEAR EAST)               Bangladesh      29.80
2          ASIA (EX. NEAR EAST)                   Bhutan      33.65
3          ASIA (EX. NEAR EAST)                   Brunei      18.79
4          ASIA (EX. NEAR EAST)                    Burma      17.91
..                                   ...             ...        ...
222  WESTERN EUROPE                           San Marino      10.02
223  WESTERN EUROPE                                Spain      10.06
224  WESTERN EUROPE                               Sweden      10.27
225  WESTERN EUROPE                          Switzerland       9.71
226  WESTERN EUROPE                       United Kingdom      10.71

[227 rows x 3 columns]

In [ ]:
# 15) Veriyi istediğiniz şekilde inceleyerek bu zamana kadar öğrendiğiniz bilgilerle anlamlı 5 adet yargı cümlesi çıkartın. 

df.groupby("Region")["Infant mortality (per 1000 births)"].mean()
# Yorum 1 : Bebek ölüm ortalaması en yüksek olan kıta : 'SUB-SAHARAN AFRICA'

df.groupby("Country")["Industry"].mean().reset_index().sort_values(by="Industry", ascending=False)
# Yorum 2 : Sanayinin ekonomik ağrılıgı en fazla olan ülke : 'Equatorial Guinea'

df.groupby(["Country", "GDP ($ per capita)"])["Birthrate"].mean().reset_index().sort_values(ascending=False, by=["GDP ($ per capita)","Birthrate"])
# Yorum 3 : Ülkenin kişi başı milli geliri azaldıkça doğrum oranlarında genel bir artış mevcuttur.

df.groupby(["Country", "Literacy (%)"])["GDP ($ per capita)"].mean().reset_index().sort_values(by="GDP ($ per capita)", ascending=False)
# Yorum 4 : Okuma oranı arttıkça kişi başı milli gelir de artar.

df["Literacy (%)"] = df["Literacy (%)"].fillna(df["Literacy (%)"].mean())
df.groupby(["Country", "Deathrate"])["Literacy (%)"].mean().reset_index().sort_values("Literacy (%)", ascending=False)
# Yorum 5 : Okuma-yazma oranı arttıkça ölüm oranları genel olarak azalmaktadır

           Country  Deathrate  Literacy (%)
11       Australia       7.51         100.0
67         Finland       9.86         100.0
118  Liechtenstein       7.18         100.0
4          Andorra       6.25         100.0
53         Denmark      10.36         100.0
..             ...        ...           ...
0      Afghanistan      20.34          36.0
85          Guinea      15.48          35.9
180   Sierra Leone      23.03          31.4
31    Burkina Faso      15.60          26.6
151          Niger      20.91          17.6

[223 rows x 3 columns]